# Configuration for cmake-format
# See: https://cmake-format.readthedocs.io/en/latest/configuration.html

# How wide to allow formatted cmake files
line_width: 100

# How many spaces to tab for indent
tab_size: 4

# If true, separate flow control names from their parentheses with a space
separate_ctrl_name_with_space: false

# If true, separate function names from parentheses with a space
separate_fn_name_with_space: false

# If a statement is wrapped to more than one line, than dangle the closing
# parenthesis on its own line
dangle_parens: false

# If the trailing parenthesis must be 'dangled' on its own line, then align it
# to this reference: `prefix`: the start of the statement,  `prefix-indent`:
# the start of the statement, plus one indentation  level, `child`: align to
# the column of the arguments
dangle_align: 'prefix'

# If the statement spelling length (including space and parenthesis) is
# smaller than this amount, then force reject nested layouts.
min_prefix_chars: 4

# If the statement spelling length (including space and parenthesis) is larger
# than the tab width by more than this amount, then force reject un-nested
# layouts.
max_prefix_chars: 10

# If a candidate layout is wrapped horizontally but it exceeds this many lines,
# then reject the layout.
max_lines_hwrap: 2

# What style line endings to use in the output.
line_ending: 'unix'

# Format command names consistently as 'lower' or 'upper' case
command_case: 'lower'

# Format keywords consistently as 'lower', 'upper', or 'unchanged'
keyword_case: 'unchanged'

# A list of command names which should always be wrapped
always_wrap: []

# If true, the argument lists which are known to be sortable will be sorted
# lexicographically
enable_sort: true

# If true, the parsers may infer whether or not an argument list is sortable
# (without annotation).
autosort: false

# By default, if cmake-format cannot successfully parse something it will print
# the parse tree and exit with an error code. However, cmake-format can also
# just print out the original text of unparsed content. In which case the
# round trip will be successful, but cmake-format will not be able to do
# anything with the unformatted regions.
require_valid_layout: false

# A dictionary mapping layout nodes to a list of wrap decisions. See the
# documentation for more information.
layout_passes: {}

# A list of patterns to exclude files from formatting
exclude_patterns: [
  '*/build/*',
  '*/.*',
]
