# Pre-commit configuration for DeclarativeUI (Local Testing Version)
# This is a minimal version for testing without network dependencies

repos:
  # Local hooks that don't require downloading
  - repo: local
    hooks:
      # Check for large files
      - id: check-large-files
        name: Check for large files
        entry: python
        args: ['-c', 'import sys, os; [sys.exit(1) if os.path.getsize(f) > 500*1024 else None for f in sys.argv[1:]]']
        language: system
        files: .

      # Remove trailing whitespace
      - id: trailing-whitespace
        name: Remove trailing whitespace
        entry: python
        args: ['-c', 'import sys; [open(f, "w").write(open(f).read().rstrip() + "\n") for f in sys.argv[1:]]']
        language: system
        files: \.(cpp|hpp|h|c|cc|cxx|cmake|txt|md|yml|yaml)$

      # Check for merge conflict markers
      - id: check-merge-conflict
        name: Check for merge conflicts
        entry: python
        args: ['-c', 'import sys, re; [sys.exit(1) if re.search(r"^(<{7}|={7}|>{7})", open(f).read(), re.M) else None for f in sys.argv[1:]]']
        language: system
        files: .

# Configuration for different CI environments
ci:
  skip: []  # Run all hooks in CI
