site_name: DeclarativeUI Framework
site_description: A modern, declarative UI framework for Qt applications
site_author: DeclarativeUI Contributors
site_url: https://declarativeui.github.io/DeclarativeUI/

repo_name: DeclarativeUI/DeclarativeUI
repo_url: https://github.com/DeclarativeUI/DeclarativeUI
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 DeclarativeUI Contributors

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang: en

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: DeclarativeUI
      repo: DeclarativeUI
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Overview: overview.md
    - Installation: user-guide/getting-started.md
    - Quick Start: user-guide/quick-start.md
  - User Guide:
    - Best Practices: user-guide/best-practices.md
    - Component System: user-guide/components.md
    - Command System: user-guide/commands.md
    - State Management: user-guide/state-management.md
    - Integration: integration-guide.md
  - API Reference:
    - Core: api/core.md
    - Components: api/components.md
    - Command System: api/command.md
    - State Management: api/binding.md
    - JSON Support: api/json.md
    - Hot Reload: api/hot-reload.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Component Examples: examples/components.md
    - Command Examples: examples/command.md
    - Advanced Examples: examples/advanced.md
  - Development:
    - Architecture: developer/architecture.md
    - Contributing: developer/contributing.md
    - Testing: developer/testing.md
    - Building: developer/building.md
  - About:
    - Changelog: changelog.md
    - License: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DeclarativeUI/DeclarativeUI
  version:
    provider: mike
