name: 🐛 Bug Report
description: Report a bug or issue with DeclarativeUI
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Module
      description: Which component or module is affected?
      options:
        - Core Framework
        - Components Library
        - Command System
        - JSON Support
        - Hot Reload
        - State Management
        - Animation Engine
        - Build System
        - Documentation
        - Examples
        - Tests
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: DeclarativeUI Version
      description: What version of DeclarativeUI are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - Ubuntu 20.04
        - Ubuntu 22.04
        - macOS 11
        - macOS 12
        - macOS 13
        - Other Linux
        - Other
    validations:
      required: true

  - type: input
    id: qt-version
    attributes:
      label: Qt Version
      description: What version of Qt6 are you using?
      placeholder: "6.5.0"
    validations:
      required: true

  - type: input
    id: compiler
    attributes:
      label: Compiler
      description: What compiler are you using?
      placeholder: "GCC 11.2, Clang 14, MSVC 2022"
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample that reproduces the issue
      render: cpp
      placeholder: |
        #include "DeclarativeUI.hpp"

        int main() {
            // Your code here
        }

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add any error messages or logs
      render: text
      placeholder: Paste error messages here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this with the latest version of DeclarativeUI
          required: true
