blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/DeclarativeUI/DeclarativeUI/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://declarativeui.github.io/DeclarativeUI/
    about: Check our comprehensive documentation and guides
  - name: 🚀 Examples
    url: https://github.com/DeclarativeUI/DeclarativeUI/tree/main/examples
    about: Browse example applications and code samples
